name: getopt-generics
version: "0.13"
category: "Console, System"
synopsis:    Create command line interfaces with ease
description: Create command line interfaces with ease
license: "BSD3"
author: "Linh Nguyen, Sönke Hahn"
copyright: "Zalora South East Asia Pte Ltd"
maintainer: "linh.nguyen@zalora.com, soenkehahn@gmail.com"

ghc-options: -Wall -fno-warn-name-shadowing

extra-source-files:
  - docs/*

dependencies:
  - base == 4.*
  - base-compat >= 0.8
  - base-orphans
  - generics-sop >= 0.1 && < 0.4
  - tagged

library:
  source-dirs:
    - src
  exposed-modules:
    - WithCli
    - WithCli.Pure

tests:
  spec:
    main: "Spec.hs"
    ghc-options: "-threaded -O0"
    source-dirs:
      - src
      - test
      - docs

    dependencies:
      - hspec >= 2.1.8
      - QuickCheck
      - silently
      - filepath
      - safe

github: soenkehahn/getopt-generics
